#!/usr/bin/julia
using Comonicon
using AllocationOpt

"""
Optimises an indexer's allocations and pushes them to the action queue.

# Arguments

- `id`: The id of the indexer to optimise.
- `filepath`: A path to the CSV file that contains whitelist, blacklist, pinnedlist, frozenlist as columns.
- `grtgas`: The maximum amount of GRT that you are willing to spend on each allocation transaction.
- `minimum_allocation_amount`: The minimum amount of GRT that you are willing to allocate to a subgraph.
- `maximum_new_allocations`: The maximum number of new allocations you would like the optimizer to open.
- `τ`: Interval [0,1]. As τ gets closer to 0, the optimiser selects greedy allocations that maximise your short-term, expected rewards, but network dynamics will affect you more. The opposite occurs as τ approaches 1. 
- `management_server_url`: The URL that exposes the indexer managment server, including the port. Must begin with http. Example: http://localhost:18000.
- `indexer_service_network_url`: The URL that exposes the indexer service's network endpoint. Must begin with http. Example: http://localhost:7600/network.
"""
@cast function actionqueue(id, filepath, minimum_allocation_amount, maximum_new_allocations, τ, management_server_url, indexer_service_network_url)
    # Read subgraph lists defined in the file
    cols = read_filterlists(filepath)

    # Pull network state from indexer service network endpoint
    indexer, repo = network_state(id, cols..., indexer_service_network_url)

    # Pull full network state from indexer service network endpoint
    _, fullrepo = network_state(id, String[], String[], String[], String[], indexer_service_network_url)

    # Optimize for the indexer
    ω = optimize_indexer(indexer, repo, fullrepo, parse(Float64, minimum_allocation_amount), parse(Int64, maximum_new_allocations), parse(Float64, τ))
    
    # Push results to action queue
    _ = push_allocations!(id, management_server_url, indexer_service_network_url, ω, cols...)

    println("Done!")

    return nothing
end

"""
Optimises an indexer's allocations and generates indexer rules to change allocations.

# Arguments

- `id`: The id of the indexer to optimise.
- `filepath`: A path to the CSV file that contains whitelist, blacklist, pinnedlist, frozenlist as columns.
- `grtgas`: The maximum amount of GRT that you are willing to spend on each allocation transaction.
- `minimum_allocation_amount`: The minimum amount of GRT that you are willing to allocate to a subgraph.
- `maximum_new_allocations`: The maximum number of new allocations you would like the optimizer to open.
- `τ`: Interval [0,1]. As τ gets closer to 0, the optimiser selects greedy allocations that maximise your short-term, expected rewards, but network dynamics will affect you more. The opposite occurs as τ approaches 1.
- `indexer_service_network_url`: The URL that exposes the indexer service's network endpoint. Must begin with http. Example: http://localhost:7600/network.
"""
@cast function rules(id, filepath, minimum_allocation_amount, maximum_new_allocations, τ, indexer_service_network_url)
    # Read subgraph lists defined in the file
    cols = read_filterlists(filepath)

    # Pull network state from indexer service network endpoint
    repo, indexer = network_state(id, cols..., indexer_service_network_url)

    # Pull full network state from indexer service network endpoint
    fullrepo, _ = network_state(id, String[], String[], String[], String[], indexer_service_network_url)

    # Optimize for the indexer
    ω = optimize_indexer(indexer, repo, fullrepo, parse(Float64, minimum_allocation_amount), parse(Int64, maximum_new_allocations), parse(Float64, τ))

    # Create indexer rules
    indexer_rules = create_rules!(id, indexer_service_network_url, ω, cols...)
    
    println.(indexer_rules)

    return nothing
end

@main
