#!/usr/bin/julia
using Comonicon
using AllocationOpt

"""
Optimises an indexer's allocations and pushes them to the action queue.

# Arguments

- `id`: The id of the indexer to optimise.
- `filepath`: A path to the CSV file that contains whitelist, blacklist, pinnedlist, frozenlist as columns.
- `grtgas`: The maximum amount of GRT that you are willing to spend on each allocation transaction.
- `minimum_allocation_amount`: The minimum amount of GRT that you are willing to allocate to a subgraph.
- `allocation_lifetime`: The number of epoches you assume to open each allocations for. Lifetime 1 means an epoch should be closed in its second epoch
- `management_server_url`: The URL that exposes the indexer managment server, including the port. Must begin with http. Example: http://localhost:18000.
- `indexer_service_network_url`: The URL that exposes the indexer service's network endpoint. Must begin with http. Example: http://localhost:7600/network.
"""
@cast function actionqueue(id, filepath, minimum_allocation_amount, maximum_new_allocations, management_server_url, indexer_service_network_url)
    # Read subgraph lists defined in the file
    cols = read_filterlists(filepath)

    # Pull network state from indexer service network endpoint
    indexer, repo = network_state(id, cols..., indexer_service_network_url)

    # Optimize for the indexer
    ω = optimize_indexer(repo, indexer, parse(Float64, minimum_allocation_amount), parse(Int64, maximum_new_allocations))
    
    # Push results to action queue
    _ = push_allocations!(id, management_server_url, indexer_service_network_url, ω, cols...)

    println("Done!")

    return nothing
end

"""
Optimises an indexer's allocations and generates indexer rules to change allocations.

# Arguments

- `id`: The id of the indexer to optimise.
- `filepath`: A path to the CSV file that contains whitelist, blacklist, pinnedlist, frozenlist as columns.
- `grtgas`: The maximum amount of GRT that you are willing to spend on each allocation transaction.
- `minimum_allocation_amount`: The minimum amount of GRT that you are willing to allocate to a subgraph.
- `allocation_lifetime`: The number of epoches you assume to open each allocations for. Lifetime 1 means an epoch should be closed in its second epoch
- `indexer_service_network_url`: The URL that exposes the indexer service's network endpoint. Must begin with http. Example: http://localhost:7600/network.
"""
@cast function rules(id, filepath, minimum_allocation_amount, maximum_new_allocations, indexer_service_network_url)
    # Read subgraph lists defined in the file
    cols = read_filterlists(filepath)

    # Pull network state from indexer service network endpoint
    indexer, repo = network_state(id, cols..., indexer_service_network_url)

    # Optimize for the indexer
    ω = optimize_indexer(repo, indexer, parse(Float64, minimum_allocation_amount), parse(Int64, maximum_new_allocations))

    # Create indexer rules
    indexer_rules = create_rules!(id, indexer_service_network_url, ω, cols...)
    
    println.(indexer_rules)

    return nothing
end

@main
